# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180620_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='teaser_html',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='teaser',
        ),
    ]
