# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20180621_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='markup',
            field=models.CharField(choices=[('html', 'Html'), ('markdown', 'Markdown')], max_length=25, verbose_name='Markup'),
        ),
    ]
