# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 15:34
# note: makemigrations keeps creating this file, even though the Image model and primary_image
# fields were never added to the database. checkin this file to repo, but effectively make it a NO-OP
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20180621_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        # migrations.RemoveField(
        #     model_name='post',
        #     name='primary_image',
        # ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
